# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Akshay Rajhans, PhD
email: arajhans@alumni.cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Akshay Rajhans.
baseurl: ""
url: ""

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


