# Site settings
title: Akshay Rajhans, PhD
email: arajhans@alumni.cmu.edu
description: Personal webpage of Dr. Akshay Rajhans
baseurl: ""
url: ""

# Footer info
affiliation: >
  Akshay Rajhans<br/>
  Head of the Advanced Research \& Technology Office and Lead Research Scientist<br/>
  MathWorks

location: >
  MathWorks<br/>
  1 Lakeside Campus Drive<br/>
  Natick, MA 01760.

contact: >
  <a href="mailto:arajhans@alumni.cmu.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Akshay via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  - name: research
  - name: software
  - name: team
  - name: teaching
  - name: blogs

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Doe
  first_name: [John]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

