title: Personal homepage of Akshay Rajhans, PhD
page-top-title: Akshay Rajhans
top-section-bg-text: Akshay Rajhans, PhD
home-subtitle: Welcome to the personal webpage of Akshay Rajhans
copyright-text: 'Akshay Rajhans 2024.'
